name = "tickle"
version = "1.0.0"

description = "Gleam Testing utility for simulating send_after delays and defining synchronization points"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "tickle" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
checkmark = ">= 1.0.0 and < 2.0.0"
